name: Full Depth

on:
  workflow_dispatch:

jobs:
  build_and_deploy_hugo_site:
    runs-on: ubuntu-latest
    name: Build and deploy Hugo site

    steps:
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.88.1'
        extended: true
    
    - name: Checkout repo -- full depth
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        token: ${{ secrets.SUBMODULE_CHALLENGE_TOKEN }}
        fetch-depth: '0'
        
    - name: Build and deploy
      uses: aormsby/hugo-deploy-to-pages@v2-post
      with:
        source_branch: 'main'
        release_branch: 'release'
        submodule_release_branch: 'main'
        # full_rebuild: true
        # test_mode: true
